# Copyright 2022 NEC Corporation
# Released under the MIT license.
# https://opensource.org/licenses/mit-license.php
#
# SDE-IMPL-RECOMMENDED REST API サーバーのポート番号を指定します
ports:
    http: 3005

# SDE-IMPL-RECOMMENDED ログレベルを次のいずれかを設定します[none/debug/info]
loglevel: debug

# SDE-MSA-PRIN 過負荷を回避する （MSA-PRIN-ID-02）
# SDE-IMPL-RECOMMENDED Backpressureの設定をします
backPressure:
    threshold: 100  # 同時実行数しきい値
    
# オペレータサービス情報
operatorService:
    session: http://localhost:3000/operator/session/
    get: http://localhost:3000/operator
    update: http://localhost:3000/operator

catalog:
    message-template: 1000359

sms:
    region: ap-northeast-1
    message_template: "%s?ID=%s パスワードは次のメッセージお送りします"
    mode: development
    country-code: +81-

phoneNumberCode: 30036

date:
    timezone: Asia/Tokyo
